### ISSUE TITLE
fail to run

### ISSUE THREAD

**Issue by everschen** [AutumnWhj/ChatGPT-wechat-bot#101]
Start to log in wechat...
23:08:37 WARN Room findAll() message.ready() rejection: Error: not logged in, no this.__currentUserId yet.
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

GError: message not found for id: 8723040437128505748
    at GError.from (file:///home/evers/ChatGPT-wechat-bot/node_modules/gerror/dist/esm/src/gerror/gerror.js:80:23)
    at PuppetWeChat.<anonymous> (file:///home/evers/ChatGPT-wechat-bot/node_modules/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:216:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on WechatyImpl instance at:
    at WechatyImpl.emit (file:///home/evers/ChatGPT-wechat-bot/node_modules/wechaty/dist/esm/src/wechaty-mixins/gerror-mixin.js:45:26)
    at PuppetWeChat.<anonymous> (file:///home/evers/ChatGPT-wechat-bot/node_modules/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:233:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'GError: message not found for id: 8723040437128505748\n' +
    '    at GError.from (file:///home/evers/ChatGPT-wechat-bot/node_modules/gerror/dist/esm/src/gerror/gerror.js:80:23)\n' +
    '    at PuppetWeChat.<anonymous> (file:///home/evers/ChatGPT-wechat-bot/node_modules/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:216:63)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}

**Comment by everschen** [comment]
it can run on the first time, but failed for second try

**Comment by AutumnWhj** [comment]
pull the code by mater branch and try again ?

**Comment by Eacolt** [comment]
怎么解决的，我也遇到了
