### ISSUE TITLE
无法登陆，扫码二维码之后显示超时

### ISSUE THREAD

**Issue by SmartPig-Joe** [AutumnWhj/ChatGPT-wechat-bot#102]
以下为报错信息
08:30:00 WARN PuppetWatchdogAgent start() reset() reason: {"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}
node:events:491
      throw er; // Unhandled 'error' event
      ^

GError: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"
    at Watchdog.reset (file:///code/node_modules/wechaty-puppet/dist/esm/src/agents/watchdog-agent.js:45:39)
    at Watchdog.emit (node:events:513:28)
    at Timeout._onTimeout (file:///code/node_modules/watchdog/dist/esm/src/watchdog.js:81:18)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
Emitted 'error' event on WechatyImpl instance at:
    at WechatyImpl.emit (file:///code/node_modules/wechaty/dist/esm/src/wechaty-mixins/gerror-mixin.js:45:26)
    at PuppetWeChat.<anonymous> (file:///code/node_modules/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:155:34)
    at PuppetWeChat.emit (node:events:513:28)
    at PuppetWeChat.emit (file:///code/node_modules/wechaty-puppet/dist/esm/src/puppet/puppet-skeleton.js:107:22)
    at Watchdog.reset (file:///code/node_modules/wechaty-puppet/dist/esm/src/agents/watchdog-agent.js:45:25)
    at Watchdog.emit (node:events:513:28)
    [... lines matching original stack trace ...]
    at processTimers (node:internal/timers:502:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (file:///code/node_modules/wechaty-puppet/dist/esm/src/agents/watchdog-agent.js:45:39)\n' +
    '    at Watchdog.emit (node:events:513:28)\n' +
    '    at Timeout._onTimeout (file:///code/node_modules/watchdog/dist/esm/src/watchdog.js:81:18)\n' +
    '    at listOnTimeout (node:internal/timers:559:17)\n' +
    '    at processTimers (node:internal/timers:502:7)'
}

**Comment by AutumnWhj** [comment]
你好 可重新拉代码试试

**Comment by pengtianyua** [comment]
> 你好 可重新拉代码试试

你好 最新代码扫完码还是一样的问题

**Comment by pengtianyua** [comment]
> 

![image](https://user-images.githubusercontent.com/55934798/216559121-be5457b6-cf57-4f24-aaa5-fac6a49266ae.png)
这是报错信息

**Comment by pengtianyua** [comment]
> 你好 可重新拉代码试试

好像是微信没有实名认证的问题

**Comment by SmartPig-Joe** [comment]
我试了一下直接点开微信网页版，扫码，也是登录不了，是不是因为这个原因导致这里登陆不了

**Comment by syyang2022** [comment]
> 

试了一下，的确这样，有什么解决办法么，其他人都可以直接登录么？
