### ISSUE TITLE
我根据最新的代码创建了现成的Docker镜像，并上传到了Docker HUB

### ISSUE THREAD

**Issue by suyunkai** [AutumnWhj/ChatGPT-wechat-bot#104]
https://hub.docker.com/r/suyunkai46/chatgpt-wechat
需注意：
1、启动参数需要加上-dit，否则会马上自己关闭。
2、需要挂载容器内的/code/src/config.ts文件，然后修改它，加上openapi参数。
3、启动容器后控制台运行npm run dev即可扫码
4、可以在控制台输入npm install -g pm2，安装pm2。然后用pm2 start npm -- run dev命令启动程序，这样的话，随时可以输入指令pm2 logs查看日志记录。

**Comment by huweinan** [comment]
ChatGPT invalid apiKey 镜像启动报这个错是什么意思？

**Comment by wanglong167** [comment]
一直回复的英文啊

**Comment by soboker** [comment]
微信群，触发关键字可以用中文么？ 我现在怎么发都触发不了群回复。

**Comment by znkey** [comment]
没有config.ts文件,src里面是空的。是我哪里错了吗？请指教下，谢谢！

**Comment by 17huiwei** [comment]
楼主，能给个完整的安装命令行么？我等小白只能看代码分析

**Comment by liuruidong4** [comment]
可以的！

**Comment by liuruidong4** [comment]
> 楼主，能给个完整的安装命令行么？我等小白只能看代码分析

进src目录 docker run -itd --name wechatbot -v pwd:/code/src suyunkai46/chatgpt-wechat  挂载一下src文件夹配置就是
docker exec -it wechatbot bash  进去容器里
npm run dev  
然后等着扫码  就完事了

**Comment by 17huiwei** [comment]
> pm2 logs

特别感谢！

**Comment by 17huiwei** [comment]
> 没有config.ts文件,src里面是空的。是我哪里错了吗？请指教下，谢谢！

自己下载，然后映射

**Comment by huluohu** [comment]
> https://hub.docker.com/r/suyunkai46/chatgpt-wechat 需注意： 1、启动参数需要加上-dit，否则会马上自己关闭。 2、需要挂载容器内的/code/src/config.ts文件，然后修改它，加上openapi参数。 3、启动容器后控制台运行npm run dev即可扫码 4、可以在控制台输入npm install -g pm2，安装pm2。然后用pm2 start npm -- run dev命令启动程序，这样的话，随时可以输入指令pm2 logs查看日志记录。

大佬，您构建镜像的dockerfile能共享下吗，目前源码里的dockerfile貌似跟实际代码配置有差异，构建一直报错。

**Comment by hetaozhen** [comment]
> 一直回复的英文啊

你得要求它跟你说中文，它就会说了

**Comment by s0ng1** [comment]
代码更新了，可以发布个新版的docker吗？

**Comment by whitexiong** [comment]
我挂 pm2 一直后启动后一段时间后报错启动不起来是怎么回事？
![image](https://user-images.githubusercontent.com/30070536/217406198-2035436f-b7e2-4220-82bf-d2cba48c5b80.png)

**Comment by znkey** [comment]
> > 没有config.ts文件,src里面是空的。是我哪里错了吗？请指教下，谢谢！
> 
> 自己下载，然后映射

OK. 我下载源代码上传到映射的文件夹然后重启容器,能启动了.感谢！

**Comment by suyunkai** [comment]
> > https://hub.docker.com/r/suyunkai46/chatgpt-wechat 需注意： 1、启动参数需要加上-dit，否则会马上自己关闭。2、需要挂载容器内的/code/src/config.ts文件，然后修改它，加上openapi参数。3、启动容器后控制台运行npm run dev即可扫码 4、可以在控制台输入npm install -g pm2，安装pm2。然后用pm2 start npm -- run dev命令启动程序，这样的话，随时可以输入指令pm2 logs查看日志记录。
> 
> 大佬，您构建镜像的dockerfile能共享下吗，目前源码里的dockerfile貌似跟实际代码配置有差异，构建一直报错。
以下是我的构建代码，能成功构建

FROM node:18
WORKDIR /code
ADD package.json package-lock.json /code/
RUN apt-get update && apt-get install -y apt-utils
RUN apt-get update -qq && apt-get install -y -qq curl
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get update -qq && apt-get install -y -qq nodejs
# Suppress an apt-key warning about standard out not being a terminal. Use in this script is safe.
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
# Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteer
# installs, work.
#去除了wget的安装，将wget的安装和chrome的安装都打包成了docker镜像。
#在没有科学上网的设备上，可能因为网络问题无法下载linux_signing_key.pub文件而进度卡住（如服务器搭建不方便搭梯子）
RUN apt-get update \
  && apt-get install -y wget gnupg \
  && wget -q -O - https://gitlab.com/yyc5/test/-/raw/a7ed9e5920614037a6c35a1076c2197dae8f5b0f/linux_signing_key.pub?inline=false | apt-key add - \
  && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
  && apt-get update \
  && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
  --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*
ADD . /code
RUN npm i 
RUN npm install -g npm@9.2.0
#此dockerfile文件引导完，需要进一步操作，请看readme文件。引导过程有部分爆红不影响，进度一直向下等待build 好即可。
# Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteery

**Comment by xunzhimeng** [comment]
能否把dockerfile最新的发一下，上面那个没法搞

**Comment by TaiFSG** [comment]
Debugger listening on ws://127.0.0.1:9229/4c0c4e41-f890-4084-87a7-6b23a8a9758a
For help, see: https://nodejs.org/en/docs/inspector
(node:36) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
init error:  Error: ChatGPT invalid apiKey
    at new ChatGPTAPI (file:///code/node_modules/chatgpt/src/chatgpt-api.ts:117:13)
    at initChatGPT (file:///code/src/chatgpt.ts:8:13)
    at initProjest (file:///code/src/index.ts:87:11)
    at file:///code/src/index.ts:7:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

请问这个本地挂载文件是放到哪个目录，服务器上有这个，但是启动就找不到呢

**Comment by huluohu** [comment]
> > > https://hub.docker.com/r/suyunkai46/chatgpt-wechat 需注意： 1、启动参数需要加上-dit，否则会马上自己关闭。2、需要挂载容器内的/code/src/config.ts文件，然后修改它，加上openapi参数。3、启动容器后控制台运行npm run dev即可扫码 4、可以在控制台输入npm install -g pm2，安装pm2。然后用pm2 start npm -- run dev命令启动程序，这样的话，随时可以输入指令pm2 logs查看日志记录。
> > 
> > 
> > 大佬，您构建镜像的dockerfile能共享下吗，目前源码里的dockerfile貌似跟实际代码配置有差异，构建一直报错。
> > 以下是我的构建代码，能成功构建
> 
> FROM node:18 WORKDIR /code ADD package.json package-lock.json /code/ RUN apt-get update && apt-get install -y apt-utils RUN apt-get update -qq && apt-get install -y -qq curl RUN curl -sL https://deb.nodesource.com/setup_18.x | bash - RUN apt-get update -qq && apt-get install -y -qq nodejs
> 
> # Suppress an apt-key warning about standard out not being a terminal. Use in this script is safe.
> ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
> 
> # Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
> # Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteer
> # installs, work.
> #去除了wget的安装，将wget的安装和chrome的安装都打包成了docker镜像。 #在没有科学上网的设备上，可能因为网络问题无法下载linux_signing_key.pub文件而进度卡住（如服务器搭建不方便搭梯子） RUN apt-get update && apt-get install -y wget gnupg && wget -q -O - https://gitlab.com/yyc5/test/-/raw/a7ed9e5920614037a6c35a1076c2197dae8f5b0f/linux_signing_key.pub?inline=false | apt-key add - && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && apt-get update && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 --no-install-recommends && rm -rf /var/lib/apt/lists/* ADD . /code RUN npm i RUN npm install -g npm@9.2.0 #此dockerfile文件引导完，需要进一步操作，请看readme文件。引导过程有部分爆红不影响，进度一直向下等待build 好即可。
> 
> # Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteery

非常感谢。

**Comment by whao123yahoo** [comment]
> > > 没有config.ts文件,src里面是空的。是我哪里错了吗？请指教下，谢谢！
> > 
> > 自己下载，然后映射
> 
> OK. 我下载源代码上传到映射的文件夹然后重启容器,能启动了.感谢！

在哪里下载的😂

**Comment by Jas0nxlee** [comment]
启动后报错如下：
retry 1 times, error: Error: ChatGPT error 503: {
  "error": {
    "message": "That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID edf1df32ea4f50e2af3a2c16494d090b in your message.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}



retry 2 times, error: Error: ChatGPT error 503: {
  "error": {
    "message": "That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 18776f23d0a098847963e33fd70058ae in your message.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}

**Comment by whao123yahoo** [comment]
不是说了吗，满负载了

发自我的小米
在 Jas0nxlee ***@***.***>，2023年2月9日 10:12写道：

启动后报错如下：
retry 1 times, error: Error: ChatGPT error 503: {
"error": {
"message": "That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID edf1df32ea4f50e2af3a2c16494d090b in your message.)",
"type": "server_error",
"param": null,
"code": null
}
}

retry 2 times, error: Error: ChatGPT error 503: {
"error": {
"message": "That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 18776f23d0a098847963e33fd70058ae in your message.)",
"type": "server_error",
"param": null,
"code": null
}
}

**Comment by suyunkai** [comment]
补充：docker hub里，latest版本是chatgpt的api，现在已经不能用了。3.0版本是GPT3的API，可用

**Comment by FreezeStars** [comment]
> 补充：docker hub里，latest版本是chatgpt的api，现在已经不能用了。3.0版本是GPT3的API，可用

老板，那现在你这个docker还能用吗？

我用的时候有点子问题
Debugger listening on ws://127.0.0.1:9229/d153cebf-841d-4f5c-a243-9244578afea6
For help, see: https://nodejs.org/en/docs/inspector
(node:43) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
init error:  Error: ChatGPT invalid apiKey
    at new ChatGPTAPI (file:///code/node_modules/chatgpt/src/chatgpt-api.ts:117:13)
    at initChatGPT (file:///code/src/chatgpt.ts:8:13)
    at initProjest (file:///code/src/index.ts:87:11)
    at file:///code/src/index.ts:7:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

这个咋整？

**Comment by FreezeStars** [comment]
老板，所以现在api还能用吗？
我报这个错：
Debugger listening on ws://127.0.0.1:9229/62e4b35d-b2fd-43ae-baf9-aea768a66aee
For help, see: https://nodejs.org/en/docs/inspector
(node:2247) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/code/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/index.ts:39:16 - error TS2339: Property 'autoReply' does not exist on type '{ OPENAI_API_KEY: string; reverseProxyUrl: string; groupKey: string; privateKey: string; resetKey: string; groupReplyMode: boolean; privateReplyMode: boolean; }'.

39     if (config.autoReply) {
                  ~~~~~~~~~
src/index.ts:68:14 - error TS2339: Property 'autoReply' does not exist on type '{ OPENAI_API_KEY: string; reverseProxyUrl: string; groupKey: string; privateKey: string; resetKey: string; groupReplyMode: boolean; privateReplyMode: boolean; }'.

68   if (config.autoReply) {
                ~~~~~~~~~
src/index.ts:79:16 - error TS2339: Property 'friendShipRule' does not exist on type '{ OPENAI_API_KEY: string; reverseProxyUrl: string; groupKey: string; privateKey: string; resetKey: string; groupReplyMode: boolean; privateReplyMode: boolean; }'.

79     if (config.friendShipRule.test(friendship.hello())) {
                  ~~~~~~~~~~~~~~
src/index.ts:101:16 - error TS2339: Property 'friendShipRule' does not exist on type '{ OPENAI_API_KEY: string; reverseProxyUrl: string; groupKey: string; privateKey: string; resetKey: string; groupReplyMode: boolean; privateReplyMode: boolean; }'.

101     if (config.friendShipRule) {
                   ~~~~~~~~~~~~~~

    at createTSError (/code/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/code/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/code/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/code/node_modules/ts-node/src/index.ts:1433:41)
    at transformSource (/code/node_modules/ts-node/src/esm.ts:400:37)
    at /code/node_modules/ts-node/src/esm.ts:278:53
    at async addShortCircuitFlag (/code/node_modules/ts-node/src/esm.ts:409:15)
    at async nextLoad (node:internal/modules/esm/loader:163:22)
    at async ESMLoader.load (node:internal/modules/esm/loader:605:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:11) {
  diagnosticCodes: [ 2339, 2339, 2339, 2339 ]
}
root@3e304e8958a1:/code/src# npm run dev

> chatgpt-wechatbot@1.0.0 dev
> node --loader ts-node/esm --inspect ./src/index.ts

Debugger listening on ws://127.0.0.1:9229/6811f93c-0e20-4dc2-955d-5a8d7afaa18f
For help, see: https://nodejs.org/en/docs/inspector
(node:2271) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/code/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/index.ts:39:16 - error TS2339: Property 'autoReply' does not exist on type '{ OPENAI_API_KEY: string; reverseProxyUrl: string; groupKey: string; privateKey: string; resetKey: string; groupReplyMode: boolean; privateReplyMode: boolean; }'.

39     if (config.autoReply) {
                  ~~~~~~~~~
src/index.ts:68:14 - error TS2339: Property 'autoReply' does not exist on type '{ OPENAI_API_KEY: string; reverseProxyUrl: string; groupKey: string; privateKey: string; resetKey: string; groupReplyMode: boolean; privateReplyMode: boolean; }'.

68   if (config.autoReply) {
                ~~~~~~~~~
src/index.ts:79:16 - error TS2339: Property 'friendShipRule' does not exist on type '{ OPENAI_API_KEY: string; reverseProxyUrl: string; groupKey: string; privateKey: string; resetKey: string; groupReplyMode: boolean; privateReplyMode: boolean; }'.

79     if (config.friendShipRule.test(friendship.hello())) {
                  ~~~~~~~~~~~~~~
src/index.ts:101:16 - error TS2339: Property 'friendShipRule' does not exist on type '{ OPENAI_API_KEY: string; reverseProxyUrl: string; groupKey: string; privateKey: string; resetKey: string; groupReplyMode: boolean; privateReplyMode: boolean; }'.

101     if (config.friendShipRule) {
                   ~~~~~~~~~~~~~~

    at createTSError (/code/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/code/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/code/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/code/node_modules/ts-node/src/index.ts:1433:41)
    at transformSource (/code/node_modules/ts-node/src/esm.ts:400:37)
    at /code/node_modules/ts-node/src/esm.ts:278:53
    at async addShortCircuitFlag (/code/node_modules/ts-node/src/esm.ts:409:15)
    at async nextLoad (node:internal/modules/esm/loader:163:22)
    at async ESMLoader.load (node:internal/modules/esm/loader:605:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:11) {
  diagnosticCodes: [ 2339, 2339, 2339, 2339 ]
}
老板瞅瞅
