### ISSUE TITLE
heartbeat@browserbridge ding

### ISSUE THREAD

**Issue by finalcreator** [AutumnWhj/ChatGPT-wechat-bot#116]
06:40:40 WARN PuppetWatchdogAgent start() reset() reason: {"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}
file:///opt/ChatGPT-wechat-bot/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65
      this.puppet.emit('error', new Error(
                                ^
GError: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"
    at Watchdog.reset (file:///opt/ChatGPT-wechat-bot/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
    at Watchdog.emit (node:events:513:28)
    at Watchdog.emit (node:domain:489:12)
    at Timeout._onTimeout (file:///opt/ChatGPT-wechat-bot/node_modules/watchdog/src/watchdog.ts:115:12)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (file:///opt/ChatGPT-wechat-bot/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
    '    at Watchdog.emit (node:events:513:28)\n' +
    '    at Watchdog.emit (node:domain:489:12)\n' +
    '    at Timeout._onTimeout (file:///opt/ChatGPT-wechat-bot/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
    '    at listOnTimeout (node:internal/timers:564:17)\n' +
    '    at processTimers (node:internal/timers:507:7)'
}
2023/02/06 08:04:59.042030 cmd_run.go:1046: WARNING: cannot create user data directory: failed to verify SELinux context of /root/snap: exec: "matchpathcon": executable file not found in $PATH
2023/02/06 08:04:59.153512 cmd_run.go:1046: WARNING: cannot create user data directory: failed to verify SELinux context of /root/snap: exec: "matchpathcon": executable file not found in $PATH

**Comment by davideuler** [comment]
微信号需要实名认证的

**Comment by GaleForceWYL21** [comment]
实名认证了还是会出现同样的问题

**Comment by GaleForceWYL21** [comment]
> 

想问一下，我已经实名认证，仍然会每隔2个小时报一次这个错，只能重启。请问您有遇到类似的问题吗

**Comment by jetzfly** [comment]
> > 
> 
> 想问一下，我已经实名认证，仍然会每隔2个小时报一次这个错，只能重启。请问您有遇到类似的问题吗

同样的问题。

**Comment by xuHong-lukan** [comment]
不要再发邮件了，警告！发自我的荣耀手机-------- 原始邮件 --------发件人： Jeffrey ***@***.***>日期： 2023年4月18日周二 18:13收件人： AutumnWhj/ChatGPT-wechat-bot ***@***.***>抄送： Subscribed ***@***.***>主    题： Re: [AutumnWhj/ChatGPT-wechat-bot] ***@***.*** ding (Issue #116)



想问一下，我已经实名认证，仍然会每隔2个小时报一次这个错，只能重启。请问您有遇到类似的问题吗

同样的问题。

**Comment by motivated3** [comment]
遇到了同样的问题，求问咋解？

**Comment by maxoyed** [comment]
同样的问题，请问有解决方案么？

**Comment by liyancai** [comment]
同样的问题
 Error: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"

报这个错误，然后就死掉了，只能手动重启
