### ISSUE TITLE
求详细教程

### ISSUE THREAD

**Issue by chandler0714** [AutumnWhj/ChatGPT-wechat-bot#120]
能否提供一个更为详细的教程给小白呢？docker形式看了很多教程好像现在不能用了，有搬瓦工的服务器可以不熟吗？远程ssh上之后安装了node和npm但是npm i和dev时候报了大量的错误。直接从git上拉的文件到服务器上修改了config.ts文件，但是还是npm还是报错。。。求助一个详细的配置步骤。

**Comment by 0x00A0** [comment]
放一下具体的报错信息吧,方便debug

**Comment by chandler0714** [comment]
npm ERR! Linux 4.15.0-20-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm ERR! Linux 4.15.0-20-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

**Comment by chandler0714** [comment]
> 放一下具体的报错信息吧,方便debug

npm ERR! Linux 4.15.0-20-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm ERR! Linux 4.15.0-20-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

提示很长，这是其中一段

**Comment by 0x00A0** [comment]
> > 放一下具体的报错信息吧,方便debug
> 
> npm ERR! Linux 4.15.0-20-generic npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" npm ERR! node v8.10.0 npm ERR! npm v3.5.2 npm ERR! code EMISSINGARG
> 
> npm ERR! typeerror Error: Missing required argument #1 npm ERR! typeerror at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3) npm ERR! typeerror at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22) npm ERR! typeerror at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12) npm ERR! typeerror at /usr/share/npm/lib/install/deps.js:457:7 npm ERR! typeerror at /usr/share/npm/node_modules/iferr/index.js:13:50 npm ERR! typeerror at /usr/share/npm/lib/fetch-package-metadata.js:37:12 npm ERR! typeerror at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5) npm ERR! typeerror at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7) npm ERR! typeerror at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20) npm ERR! typeerror at /usr/share/npm/node_modules/iferr/index.js:13:50 npm ERR! typeerror This is an error with npm itself. Please report this error at: npm ERR! typeerror [http://github.com/npm/npm/issues](https://github.com/npm/npm/issues) npm ERR! Linux 4.15.0-20-generic npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" npm ERR! node v8.10.0 npm ERR! npm v3.5.2 npm ERR! code EMISSINGARG
> 
> 提示很长，这是其中一段

请先更新Node和npm版本,至少需要Node v18以上

---
建议以下方式更新node:
```bash
#清除npm缓存
npm cache clean -f
#安装n模块
npm install -g n
#升级node.js到最新稳定版
n stable
```

**Comment by chandler0714** [comment]
> > > 放一下具体的报错信息吧,方便debug
> > 
> > 
> > npm ERR! Linux 4.15.0-20-generic npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" npm ERR! node v8.10.0 npm ERR! npm v3.5.2 npm ERR! code EMISSINGARG
> > npm ERR! typeerror Error: Missing required argument #1 npm ERR! typeerror at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3) npm ERR! typeerror at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22) npm ERR! typeerror at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12) npm ERR! typeerror at /usr/share/npm/lib/install/deps.js:457:7 npm ERR! typeerror at /usr/share/npm/node_modules/iferr/index.js:13:50 npm ERR! typeerror at /usr/share/npm/lib/fetch-package-metadata.js:37:12 npm ERR! typeerror at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5) npm ERR! typeerror at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7) npm ERR! typeerror at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20) npm ERR! typeerror at /usr/share/npm/node_modules/iferr/index.js:13:50 npm ERR! typeerror This is an error with npm itself. Please report this error at: npm ERR! typeerror [http://github.com/npm/npm/issues](https://github.com/npm/npm/issues) npm ERR! Linux 4.15.0-20-generic npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" npm ERR! node v8.10.0 npm ERR! npm v3.5.2 npm ERR! code EMISSINGARG
> > 提示很长，这是其中一段
> 
> 请先更新Node和npm版本,至少需要Node v18以上
> 
> 建议以下方式更新node:
> 
> ```shell
> #清除npm缓存
> npm cache clean -f
> #安装n模块
> npm install -g n
> #升级node.js到最新稳定版
> n stable
> ```

刚更新了一下最新版本竟然只到16，我重新装一下试试，感谢

**Comment by chandler0714** [comment]
> > > 放一下具体的报错信息吧,方便debug
> > 
> > 
> > npm ERR! Linux 4.15.0-20-generic npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" npm ERR! node v8.10.0 npm ERR! npm v3.5.2 npm ERR! code EMISSINGARG
> > npm ERR! typeerror Error: Missing required argument #1 npm ERR! typeerror at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3) npm ERR! typeerror at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22) npm ERR! typeerror at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12) npm ERR! typeerror at /usr/share/npm/lib/install/deps.js:457:7 npm ERR! typeerror at /usr/share/npm/node_modules/iferr/index.js:13:50 npm ERR! typeerror at /usr/share/npm/lib/fetch-package-metadata.js:37:12 npm ERR! typeerror at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5) npm ERR! typeerror at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7) npm ERR! typeerror at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20) npm ERR! typeerror at /usr/share/npm/node_modules/iferr/index.js:13:50 npm ERR! typeerror This is an error with npm itself. Please report this error at: npm ERR! typeerror [http://github.com/npm/npm/issues](https://github.com/npm/npm/issues) npm ERR! Linux 4.15.0-20-generic npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" npm ERR! node v8.10.0 npm ERR! npm v3.5.2 npm ERR! code EMISSINGARG
> > 提示很长，这是其中一段
> 
> 请先更新Node和npm版本,至少需要Node v18以上
> 
> 建议以下方式更新node:
> 
> ```shell
> #清除npm缓存
> npm cache clean -f
> #安装n模块
> npm install -g n
> #升级node.js到最新稳定版
> n stable
> ```


使用18之后在npm dev的时候又出现了新提示，按照网上的方式改ts和js文件都不行
(node:25104) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
SyntaxError: Unexpected token ':'
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)

**Comment by chandler0714** [comment]
调整了一下config.js文件，重新运行npm run dev后提示错误：
 details: 'Error: Failed to launch the browser process!\n' +
    '/root/ChatGPT-wechat-bot/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory\n' +

**Comment by kzwds** [comment]
![DO{@O$LZB5_D{4%MO7K4@@X.png](https://user-images.githubusercontent.com/111350122/217231466-75dd4f12-005d-41ac-bdd9-bece80b9fd64.png)

**Comment by chandler0714** [comment]
问题已解决，感谢解答

**Comment by chandler0714** [comment]
目前遇到新问题，由于我在config文件中放的是cookie中的值导致openai账户被封停了，目前没有找到联系方式解封，大家希望有人在操作时看到这个情况。。。哎从此职能告别openai了，限制太严格了
