### ISSUE TITLE
运行`npm run dev`失败，提示GError：Page crashed

### ISSUE THREAD

**Issue by qiezikuangge** [AutumnWhj/ChatGPT-wechat-bot#139]
GError: Page crashed!
    at Page._onTargetCrashed (/mnt/d/chatgpt/ChatGPT-wechat-bot-master/node_modules/puppeteer/src/common/Page.ts:774:24)
    at /mnt/d/chatgpt/ChatGPT-wechat-bot-master/node_modules/puppeteer/src/common/Page.ts:573:53
    at /mnt/d/chatgpt/ChatGPT-wechat-bot-master/node_modules/puppeteer/vendor/mitt/src/index.ts:88:75
    at Array.map (<anonymous>)
    at Object.emit (/mnt/d/chatgpt/ChatGPT-wechat-bot-master/node_modules/puppeteer/vendor/mitt/src/index.ts:88:56)
    at CDPSession.emit (/mnt/d/chatgpt/ChatGPT-wechat-bot-master/node_modules/puppeteer/src/common/EventEmitter.ts:102:18)
    at CDPSession._onMessage (/mnt/d/chatgpt/ChatGPT-wechat-bot-master/node_modules/puppeteer/src/common/Connection.ts:324:12)
    at Connection._onMessage (/mnt/d/chatgpt/ChatGPT-wechat-bot-master/node_modules/puppeteer/src/common/Connection.ts:153:28)
    at WebSocket.<anonymous> (/mnt/d/chatgpt/ChatGPT-wechat-bot-master/node_modules/puppeteer/src/node/NodeWebSocketTransport.ts:47:42)
    at WebSocket.onMessage (/mnt/d/chatgpt/ChatGPT-wechat-bot-master/node_modules/puppeteer/node_modules/ws/lib/event-target.js:199:18) {
  code: 2,
  details: 'Error: Page crashed!\n' +
    '    at Page._onTargetCrashed (/mnt/d/chatgpt/ChatGPT-wechat-bot-master/node_modules/puppeteer/src/common/Page.ts:774:24)\n' +
    '    at /mnt/d/chatgpt/ChatGPT-wechat-bot-master/node_modules/puppeteer/src/common/Page.ts:573:53\n' +
    '    at /mnt/d/chatgpt/ChatGPT-wechat-bot-master/node_modules/puppeteer/vendor/mitt/src/index.ts:88:75\n' +
    '    at Array.map (<anonymous>)\n' +
    '    at Object.emit (/mnt/d/chatgpt/ChatGPT-wechat-bot-master/node_modules/puppeteer/vendor/mitt/src/index.ts:88:56)\n' +
    '    at CDPSession.emit (/mnt/d/chatgpt/ChatGPT-wechat-bot-master/node_modules/puppeteer/src/common/EventEmitter.ts:102:18)\n' +
    '    at CDPSession._onMessage (/mnt/d/chatgpt/ChatGPT-wechat-bot-master/node_modules/puppeteer/src/common/Connection.ts:324:12)\n' +
    '    at Connection._onMessage (/mnt/d/chatgpt/ChatGPT-wechat-bot-master/node_modules/puppeteer/src/common/Connection.ts:153:28)\n' +
    '    at WebSocket.<anonymous> (/mnt/d/chatgpt/ChatGPT-wechat-bot-master/node_modules/puppeteer/src/node/NodeWebSocketTransport.ts:47:42)\n' +
    '    at WebSocket.onMessage (/mnt/d/chatgpt/ChatGPT-wechat-bot-master/node_modules/puppeteer/node_modules/ws/lib/event-target.js:199:18)'
}

**Comment by FreezeStars** [comment]
解决了吗？我也是这个问题
