### ISSUE TITLE
npm i 出现问题

### ISSUE THREAD

**Issue by snowyseaons** [AutumnWhj/ChatGPT-wechat-bot#148]
请问是直接运行 npm i 吗？还是需要先docker build ?
/usr/local/lib/node_modules/npm/lib/cli.js:48
    throw err
    ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd [as cwd] (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/depd/index.js:25:24)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/agentkeepalive/lib/agent.js:6:19)
    at Module._compile (node:internal/modules/cjs/loader:1226:14) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}

Node.js v18.14.0

**Comment by xingdiyou** [comment]
> 请问是直接运行 npm i 吗？还是需要先docker build ? /usr/local/lib/node_modules/npm/lib/cli.js:48 throw err ^
> 
> Error: ENOENT: no such file or directory, uv_cwd at process.wrappedCwd [as cwd] (node:internal/bootstrap/switches/does_own_process_state:126:28) at Object. (/usr/local/lib/node_modules/npm/node_modules/depd/index.js:25:24) at Module._compile (node:internal/modules/cjs/loader:1226:14) at Module._extensions..js (node:internal/modules/cjs/loader:1280:10) at Module.load (node:internal/modules/cjs/loader:1089:32) at Module._load (node:internal/modules/cjs/loader:930:12) at Module.require (node:internal/modules/cjs/loader:1113:19) at require (node:internal/modules/cjs/helpers:103:18) at Object. (/usr/local/lib/node_modules/npm/node_modules/agentkeepalive/lib/agent.js:6:19) at Module._compile (node:internal/modules/cjs/loader:1226:14) { errno: -2, code: 'ENOENT', syscall: 'uv_cwd' }
> 
> Node.js v18.14.0

Upgrade your npm with sudo npm install -g npm@latest

**Comment by s0ng1** [comment]
用不了百分之百是环境问题，折腾一天了

**Comment by snowyseaons** [comment]
朋友们建个群一起讨论好不好，想把它弄好 T ^ T

**Comment by snowyseaons** [comment]
> > 请问是直接运行 npm i 吗？还是需要先docker build ? /usr/local/lib/node_modules/npm/lib/cli.js:48 throw err ^
> > Error: ENOENT: no such file or directory, uv_cwd at process.wrappedCwd [as cwd] (node:internal/bootstrap/switches/does_own_process_state:126:28) at Object. (/usr/local/lib/node_modules/npm/node_modules/depd/index.js:25:24) at Module._compile (node:internal/modules/cjs/loader:1226:14) at Module._extensions..js (node:internal/modules/cjs/loader:1280:10) at Module.load (node:internal/modules/cjs/loader:1089:32) at Module._load (node:internal/modules/cjs/loader:930:12) at Module.require (node:internal/modules/cjs/loader:1113:19) at require (node:internal/modules/cjs/helpers:103:18) at Object. (/usr/local/lib/node_modules/npm/node_modules/agentkeepalive/lib/agent.js:6:19) at Module._compile (node:internal/modules/cjs/loader:1226:14) { errno: -2, code: 'ENOENT', syscall: 'uv_cwd' }
> > Node.js v18.14.0
> 
> Upgrade your npm with sudo npm install -g npm@latest

请问是直接运行 npm i && npm run dev 吗？还是需要先docker build 一下环境？
