### ISSUE TITLE
run dev失败 

### ISSUE THREAD

**Issue by destyZhu** [AutumnWhj/ChatGPT-wechat-bot#157]
Debugger listening on ws://127.0.0.1:9229/d0245b19-cc54-4567-aa3b-3d5f9941428f
For help, see: https://nodejs.org/en/docs/inspector
(node:30475) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
SyntaxError: Unexpected token '??='

请问这如何解？？？

**Comment by AutumnWhj** [comment]
检查一下是否是node版本问题？ 支持node版本> 16

**Comment by Dtyyyyyy** [comment]
![image](https://user-images.githubusercontent.com/96579381/217609517-b38decde-77cb-4b4d-8bbb-0e01f8141d2b.png)
怎么都弄不好 我是 node 18

**Comment by Dtyyyyyy** [comment]
> chatgpt-wechatbot@1.0.0 dev
> node --loader ts-node/esm --inspect ./src/index.ts

Debugger listening on ws://127.0.0.1:9229/93ce9719-0809-4fb0-a06f-516e50fbf82f
For help, see: https://nodejs.org/en/docs/inspector
(node:35501) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
01:40:08 ERR PuppetWeChatBridge start() exception: Error: Failed to launch the browser process!
/home/ubuntu/ChatGPT-wechat-bot/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

01:40:08 ERR PuppetWeChat initBridge() exception: Failed to launch the browser process!
/home/ubuntu/ChatGPT-wechat-bot/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

01:40:08 ERR PuppetWeChat initBridge() this.bridge.stop() rejection: Error: no page
GError: Failed to launch the browser process!
/home/ubuntu/ChatGPT-wechat-bot/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/ubuntu/ChatGPT-wechat-bot/node_modules/puppeteer/src/node/BrowserRunner.ts:268:9)
    at Interface.<anonymous> (/home/ubuntu/ChatGPT-wechat-bot/node_modules/puppeteer/src/node/BrowserRunner.ts:254:50)
    at Interface.emit (node:events:525:35)
    at Interface.emit (node:domain:489:12)
    at Interface.close (node:internal/readline/interface:536:10)
    at Socket.onend (node:internal/readline/interface:262:10)
    at Socket.emit (node:events:525:35)
    at Socket.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 2,
  details: 'Error: Failed to launch the browser process!\n' +
    '/home/ubuntu/ChatGPT-wechat-bot/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory\n' +
    '\n' +
    '\n' +
    'TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n' +
    '\n' +
    '    at onClose (/home/ubuntu/ChatGPT-wechat-bot/node_modules/puppeteer/src/node/BrowserRunner.ts:268:9)\n' +
    '    at Interface.<anonymous> (/home/ubuntu/ChatGPT-wechat-bot/node_modules/puppeteer/src/node/BrowserRunner.ts:254:50)\n' +
    '    at Interface.emit (node:events:525:35)\n' +
    '    at Interface.emit (node:domain:489:12)\n' +
    '    at Interface.close (node:internal/readline/interface:536:10)\n' +
    '    at Socket.onend (node:internal/readline/interface:262:10)\n' +
    '    at Socket.emit (node:events:525:35)\n' +
    '    at Socket.emit (node:domain:489:12)\n' +
    '    at endReadableNT (node:internal/streams/readable:1359:12)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:82:21)'
}

**Comment by kevinwatson2** [comment]
> Debugger listening on ws://127.0.0.1:9229/d0245b19-cc54-4567-aa3b-3d5f9941428f For help, see: https://nodejs.org/en/docs/inspector (node:30475) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time (Use `node --trace-warnings ...` to show where the warning was created) SyntaxError: Unexpected token '??='
> 
> 请问这如何解？？？
请问问题解决了吗？

**Comment by Pancat007** [comment]
报同样的错

**Comment by Pancat007** [comment]
文档有些：

Error: Failed to launch the browser process puppeteer refer to https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix

// ubuntu
sudo apt-get install chromium-browser
sudo apt-get install  ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
