### ISSUE TITLE
npm run dev失败

### ISSUE THREAD

**Issue by hanyixuanten** [AutumnWhj/ChatGPT-wechat-bot#169]
[root@BTSx7g10 ChatGPT-wechat-bot]# npm run dev

> chatgpt-wechatbot@1.0.0 dev
> node --loader ts-node/esm --inspect ./src/index.ts

Debugger listening on ws://127.0.0.1:9229/f425e3fd-7b4a-4c52-8cdc-444fda25a363
For help, see: https://nodejs.org/en/docs/inspector
(node:12372) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/opt/ChatGPT-wechat-bot/node_modules/node-gyp-build/index.js:60
  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
        ^
Error: No native build was found for platform=linux arch=x64 runtime=node abi=108 uv=1 libc=glibc node=18.12.1
    loaded from: /opt/ChatGPT-wechat-bot/node_modules/leveldown

    at Function.load.path (/opt/ChatGPT-wechat-bot/node_modules/node-gyp-build/index.js:60:9)
    at load (/opt/ChatGPT-wechat-bot/node_modules/node-gyp-build/index.js:22:30)
    at Object.<anonymous> (/opt/ChatGPT-wechat-bot/node_modules/leveldown/binding.js:1:43)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .js] (/opt/ChatGPT-wechat-bot/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)

**Comment by z992** [comment]
哈喽，请问你解决了吗？我这边现在也遇到这个问题了，方便问下你的解决方案是什么吗？
