### ISSUE TITLE
built docker和在index中填入token是否有先后顺序

### ISSUE THREAD

**Issue by peterhiking** [AutumnWhj/ChatGPT-wechat-bot#18]
按
built docker, token填入index, 运行docker
built docker, 运行docker, token填入index
两种顺序执行,扫码登录,接受到微信消息后都显示如下错误 该如何解决.

Error: ChatGPT invalid session token
    at new ChatGPTAPI (file:///code/node_modules/chatgpt/build/index.js:110:13)
    at getChatGPTReply (file:///code/lib/bundle.esm.js:12:17)
    at replyMessage (file:///code/lib/bundle.esm.js:29:29)
    at WechatyImpl.onMessage (file:///code/lib/bundle.esm.js:58:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by AutumnWhj** [comment]
@peterhiking  你好，你可以试试
1. token填入index
2. built docker
3. run docker

**Comment by peterhiking** [comment]
> @peterhiking 你好，你可以试试
> 
> 1. token填入index
> 2. built docker
> 3. run docker

十分感谢,解决了,运行的很完美!
