### ISSUE TITLE
npm run dev 后报错PuppetWeChatBridge onLoad() exception: Error: testBlockedMessage() no text found!

### ISSUE THREAD

**Issue by pro-cheng** [AutumnWhj/ChatGPT-wechat-bot#183]
前两天还能登录，昨天开始运行npm run dev 报错，出不来微信二维码，报错信息如下：

```
$ npm run dev

> chatgpt-wechatbot@1.0.0 dev
> node --loader ts-node/esm --inspect ./src/index.ts

Debugger listening on ws://127.0.0.1:9229/96206798-c213-4a6d-931e-001eaaeb8a50
For help, see: https://nodejs.org/en/docs/inspector
(node:18396) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
16:40:04 WARN WechatyPuppetMixin start() starting puppet ... timeout
16:40:04 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(WechatEveryDay)
Start to log in wechat...
16:40:50 ERR PuppetWeChatBridge onLoad() exception: Error: testBlockedMessage() no text found!
file:///D:/chatgpt/ChatGPT-wechat-bot/node_modules/wechaty-puppet-wechat/src/bridge.ts:850
      throw new Error('testBlockedMessage() no text found!')
            ^
GError: testBlockedMessage() no text found!
    at Bridge.testBlockedMessage (file:///D:/chatgpt/ChatGPT-wechat-bot/node_modules/wechaty-puppet-wechat/src/bridge.ts:850:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Bridge.readyAngular (file:///D:/chatgpt/ChatGPT-wechat-bot/node_modules/wechaty-puppet-wechat/src/bridge.ts:312:30)
    at async Bridge.onLoad (file:///D:/chatgpt/ChatGPT-wechat-bot/node_modules/wechaty-puppet-wechat/src/bridge.ts:213:7) {
  code: 2,
  details: 'Error: testBlockedMessage() no text found!\n' +
    '    at Bridge.testBlockedMessage (file:///D:/chatgpt/ChatGPT-wechat-bot/node_modules/wechaty-puppet-wechat/src/bridge.ts:850:13)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Bridge.readyAngular (file:///D:/chatgpt/ChatGPT-wechat-bot/node_modules/wechaty-puppet-wechat/src/bridge.ts:312:30)\n' +
    '    at async Bridge.onLoad (file:///D:/chatgpt/ChatGPT-wechat-bot/node_modules/wechaty-puppet-wechat/src/bridge.ts:213:7)'
}

```

**Comment by chingfeng2021** [comment]
我擦，一样的问题

**Comment by Eacolt** [comment]
求助，现在一直报这个错误，楼主有办法吗？？
