### ISSUE TITLE
求大佬们解答一下这是啥问题😭

### ISSUE THREAD

**Issue by AnjouZheng** [AutumnWhj/ChatGPT-wechat-bot#21]
C:\Code\ChatGPT-wechat-bot-master>node lib/bundle.esm.js
Start to log in wechat...
Contact<Ron> has logged in
Current time:Thu Dec 08 2022 14:11:08 GMT+0800 (中国标准时间)
Automatic robot chat mode has been activated
talker: Anjou content: hello
(node:8140) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///C:/Code/ChatGPT-wechat-bot-master/node_modules/.pnpm/chatgpt@2.0.1/node_modules/chatgpt/build/index.js:246
      throw new Error(`ChatGPT failed to refresh auth token. ${err.toString()}`);
            ^

Error: ChatGPT failed to refresh auth token. TypeError: fetch failed
    at ChatGPTAPI.refreshAccessToken (file:///C:/Code/ChatGPT-wechat-bot-master/node_modules/.pnpm/chatgpt@2.0.1/node_modules/chatgpt/build/index.js:246:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTAPI.ensureAuth (file:///C:/Code/ChatGPT-wechat-bot-master/node_modules/.pnpm/chatgpt@2.0.1/node_modules/chatgpt/build/index.js:212:12)
    at async getChatGPTReply (file:///C:/Code/ChatGPT-wechat-bot-master/lib/bundle.esm.js:14:5)
    at async replyMessage (file:///C:/Code/ChatGPT-wechat-bot-master/lib/bundle.esm.js:28:19)

Node.js v18.12.1

**Comment by AutumnWhj** [comment]
在devtool 清空浏览器缓存，重新获取session token试试

**Comment by AutumnWhj** [comment]
@AnjouZheng 参考 https://github.com/AutumnWhj/ChatGPT-wechat-bot/issues/24
