### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ts-node' imported from /root/ChatGPT-wechat-bot-master/

### ISSUE THREAD

**Issue by monfanfu** [AutumnWhj/ChatGPT-wechat-bot#223]
有遇到过的吗ubuntu 22.04

**Comment by monfanfu** [comment]
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ts-node' imported from /root/ChatGPT-wechat-bot-master/
    at packageResolve (internal/modules/esm/resolve.js:664:9)
    at moduleResolve (internal/modules/esm/resolve.js:705:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:798:11)
    at Loader.resolve (internal/modules/esm/loader.js:100:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:246:28)
    at Loader.import (internal/modules/esm/loader.js:181:28)
    at internal/process/esm_loader.js:57:31
    at initializeLoader (internal/process/esm_loader.js:62:5)
    at Object.loadESM (internal/process/esm_loader.js:67:11)
    at runMainESM (internal/modules/run_main.js:43:13) {
  code: 'ERR_MODULE_NOT_FOUND'
