### ISSUE TITLE
注册小号无法扫码登录

### ISSUE THREAD

**Issue by BurgerBurglar** [AutumnWhj/ChatGPT-wechat-bot#224]
```
'GError: type() {\n' +
    '        return this._type;\n' +
    '    }(To continue, enable Weixin Pay first.)\n' +
    '    at Function.from (file:///C:/Users/tians/Documents/Projects/gpt-mouse/node_modules/gerror/src/gerror/gerror.ts:69:17)\n' +
    '    at Bridge.onDialog (file:///C:/Users/tians/Documents/Projects/gpt-mouse/node_modules/wechaty-puppet-wechat/src/bridge.ts:190:31)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)'
```
请问必须绑定中国大陆银行卡才能做机器人吗？这也太麻烦了。

**Comment by AutumnWhj** [comment]
由于微信的限制，要绑定中国的银行卡才能使用
