### ISSUE TITLE
你需要开通微信支付，才可继续操作

### ISSUE THREAD

**Issue by eiborn** [AutumnWhj/ChatGPT-wechat-bot#232]
这个很难理解，为什么要微信支付？

08:31:16 WARN PuppetWeChatBridge onDialog() page.on(dialog) type:type() {
        return this._type;
    } message:你需要开通微信支付，才可继续操作。
file:///root/ChatGPT-wechat-bot/node_modules/.pnpm/gerror@1.0.16/node_modules/gerror/src/gerror/gerror.ts:69
      const e = new Error(payload)
                ^
GError: type() {
        return this._type;
    }(你需要开通微信支付，才可继续操作。)
    at Function.from (file:///root/ChatGPT-wechat-bot/node_modules/.pnpm/gerror@1.0.16/node_modules/gerror/src/gerror/gerror.ts:69:17)
    at Bridge.onDialog (file:///root/ChatGPT-wechat-bot/node_modules/.pnpm/wechaty-puppet-wechat@1.18.4_brolog@1.14.2_gerror@1.0.16_wechaty-puppet@1.20.2/node_modules/wechaty-puppet-wechat/src/bridge.ts:190:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'GError: type() {\n' +
    '        return this._type;\n' +
    '    }(你需要开通微信支付，才可继续操作。)\n' +
    '    at Function.from (file:///root/ChatGPT-wechat-bot/node_modules/.pnpm/gerror@1.0.16/node_modules/gerror/src/gerror/gerror.ts:69:17)\n' +
    '    at Bridge.onDialog (file:///root/ChatGPT-wechat-bot/node_modules/.pnpm/wechaty-puppet-wechat@1.18.4_brolog@1.14.2_gerror@1.0.16_wechaty-puppet@1.20.2/node_modules/wechaty-puppet-wechat/src/bridge.ts:190:31)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)'

**Comment by zousoo** [comment]
小号没有实名？
