### ISSUE TITLE
错误退出

### ISSUE THREAD

**Issue by yifan9279** [AutumnWhj/ChatGPT-wechat-bot#243]
`etails: 'Error: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (file:///workspaces/ChatGPT-wechat-bot/node_modules/.pnpm/wechaty-puppet@1.20.2_rxjs@7.8.0/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
    '    at Watchdog.emit (node:events:513:28)\n' +
    '    at Watchdog.emit (node:domain:489:12)\n' +
    '    at Timeout._onTimeout (file:///workspaces/ChatGPT-wechat-bot/node_modules/.pnpm/watchdog@0.9.2/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
    '    at listOnTimeout (node:internal/timers:573:17)\n' +
    '    at processTimers (node:internal/timers:514:7)'
}
 ELIFECYCLE  Command failed with exit code 1.`

**Comment by CoderJeffrey** [comment]
同问 你解决了吗
