### ISSUE TITLE
这这个报错怎么办

### ISSUE THREAD

**Issue by miloce** [AutumnWhj/ChatGPT-wechat-bot#25]
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/root/ChatGPT-wechat-bot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at Interface.<anonymous> (/root/ChatGPT-wechat-bot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
    at Interface.emit (node:events:406:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 2,
  details: 'Error: Failed to launch the browser process!\n' +
    '/root/ChatGPT-wechat-bot/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory\n' +
    '\n' +
    '\n' +
    'TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n' +
    '\n' +
    '    at onClose (/root/ChatGPT-wechat-bot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)\n' +
    '    at Interface.<anonymous> (/root/ChatGPT-wechat-bot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)\n' +
    '    at Interface.emit (node:events:406:35)\n' +
    '    at Interface.close (node:readline:586:8)\n' +
    '    at Socket.onend (node:readline:277:10)\n' +
    '    at Socket.emit (node:events:406:35)\n' +
    '    at endReadableNT (node:internal/streams/readable:1343:12)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:83:21)'

**Comment by AutumnWhj** [comment]
@miloce 您好，这是因为运行puppeteer 缺少某些lib, 参考dockerfile里面我apt-get安装的包。

**Comment by AutumnWhj** [comment]
@miloce 如果你是在unbuntu 你可以执行 `sudo apt-get install chromium-browser`

**Comment by miloce** [comment]
欧克已经解决了。
