### ISSUE TITLE
Error: ChatGPT failed to refresh auth token. Error: 403 Forbidden

### ISSUE THREAD

**Issue by deadjoker** [AutumnWhj/ChatGPT-wechat-bot#28]
```
Error: ChatGPT failed to refresh auth token. Error: 403 Forbidden
    at ChatGPTAPI.refreshAccessToken (file:///code/node_modules/chatgpt/build/index.js:246:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTAPI.ensureAuth (file:///code/node_modules/chatgpt/build/index.js:212:12)
    at async getChatGPTReply (file:///code/lib/bundle.esm.js:14:5)
    at async replyMessage (file:///code/lib/bundle.esm.js:29:23)
```
说是无法刷新token，时灵时不灵

**Comment by AutumnWhj** [comment]
@deadjoker 您好，试试这个https://github.com/AutumnWhj/ChatGPT-wechat-bot/issues/24   在devtool 清空浏览器缓存，重新获取session token试试。

**Comment by deadjoker** [comment]
> @deadjoker 您好，试试这个#24 在devtool 清空浏览器缓存，重新获取session token试试。

我清空了缓存，重启了系统，还是会报这个错。这个会不会有api访问频率的限制呀
