### ISSUE TITLE
微信接收消息报错

### ISSUE THREAD

**Issue by zz0001** [AutumnWhj/ChatGPT-wechat-bot#29]
我在本地控制到npm run dev 启动，扫码登录微信以后，接收到别人的消息就会报错：
Error: ChatGPT failed to refresh auth token. TypeError: _undici.fetch is not a function
    at ChatGPTAPI.refreshAccessToken (file:///Users/zz/openAI/ChatGPT-wechat-bot-master/node_modules/chatgpt/build/index.js:246:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ChatGPTAPI.ensureAuth (file:///Users/zz/openAI/ChatGPT-wechat-bot-master/node_modules/chatgpt/build/index.js:212:12)
    at async getChatGPTReply (file:///Users/zz/openAI/ChatGPT-wechat-bot-master/lib/bundle.esm.js:14:5)
    at async replyMessage (file:///Users/zz/openAI/ChatGPT-wechat-bot-master/lib/bundle.esm.js:29:23)

**Comment by h7ml** [comment]
ChatGPT failed to refresh auth token.

**Comment by acheong08** [comment]
In the process of a fix on the ChatGPT repo

**Comment by AutumnWhj** [comment]
您好，试试这个https://github.com/AutumnWhj/ChatGPT-wechat-bot/issues/24 在devtool 清空浏览器缓存，重新获取session token试试。
