### ISSUE TITLE
这个错误咋解决

### ISSUE THREAD

**Issue by zhaofuhao** [AutumnWhj/ChatGPT-wechat-bot#31]
22:49:08 ERR PuppetWeChatBridge start() exception: Error: An `executablePath` or `channel` must be specified for `puppeteer-core`
22:49:08 ERR PuppetWeChat initBridge() exception: An `executablePath` or `channel` must be specified for `puppeteer-core`
22:49:08 ERR PuppetWeChat initBridge() this.bridge.stop() rejection: Error: no page
GError: An `executablePath` or `channel` must be specified for `puppeteer-core`
    at assert (E:\机器人\ChatGPT-wechat-bot-master\ChatGPT-wechat-bot-master\node_modules\puppeteer-core\lib\cjs\puppeteer\util\assert.js:28:15)
    at ChromeLauncher.launch (E:\机器人\ChatGPT-wechat-bot-master\ChatGPT-wechat-bot-master\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ChromeLauncher.js:69:36)
    at PuppeteerNode.launch (E:\机器人\ChatGPT-wechat-bot-master\ChatGPT-wechat-bot-master\node_modules\puppeteer-core\lib\cjs\puppeteer\node\PuppeteerNode.js:154:105)
    at PuppeteerExtra.launch (E:\机器人\ChatGPT-wechat-bot-master\ChatGPT-wechat-bot-master\node_modules\puppeteer-extra\dist\index.cjs.js:128:41)
    at async Bridge.initBrowser (file:///E:/%E6%9C%BA%E5%99%A8%E4%BA%BA/ChatGPT-wechat-bot-master/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:109:23)
    at async Bridge.start (file:///E:/%E6%9C%BA%E5%99%A8%E4%BA%BA/ChatGPT-wechat-bot-master/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:48:28)
    at async PuppetWeChat.initBridge (file:///E:/%E6%9C%BA%E5%99%A8%E4%BA%BA/ChatGPT-wechat-bot-master/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:176:13)
    at async PuppetWeChat.onStart (file:///E:/%E6%9C%BA%E5%99%A8%E4%BA%BA/ChatGPT-wechat-bot-master/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:69:23)
    at async PuppetWeChat.start (file:///E:/%E6%9C%BA%E5%99%A8%E4%BA%BA/ChatGPT-wechat-bot-master/ChatGPT-wechat-bot-master/node_modules/state-switch/dist/esm/src/service-ctl/service-ctl.js:62:17)
    at async PuppetWeChat.start (file:///E:/%E6%9C%BA%E5%99%A8%E4%BA%BA/ChatGPT-wechat-bot-master/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet/dist/esm/src/mixins/service-mixin.js:18:13) {
  code: 2,
  details: 'Error: An `executablePath` or `channel` must be specified for `puppeteer-core`\n' +
    '    at assert (E:\\机器人\\ChatGPT-wechat-bot-master\\ChatGPT-wechat-bot-master\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\util\\assert.js:28:15)\n' +
    '    at ChromeLauncher.launch (E:\\机器人\\ChatGPT-wechat-bot-master\\ChatGPT-wechat-bot-master\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\node\\ChromeLauncher.js:69:36)\n' +
    '    at PuppeteerNode.launch (E:\\机器人\\ChatGPT-wechat-bot-master\\ChatGPT-wechat-bot-master\\node_modules\\puppeteer-core\\lib\\cjs\\puppeteer\\node\\PuppeteerNode.js:154:105)\n' +
    '    at PuppeteerExtra.launch (E:\\机器人\\ChatGPT-wechat-bot-master\\ChatGPT-wechat-bot-master\\node_modules\\puppeteer-extra\\dist\\index.cjs.js:128:41)\n' +
    '    at async Bridge.initBrowser (file:///E:/%E6%9C%BA%E5%99%A8%E4%BA%BA/ChatGPT-wechat-bot-master/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:109:23)\n' +
    '    at async Bridge.start (file:///E:/%E6%9C%BA%E5%99%A8%E4%BA%BA/ChatGPT-wechat-bot-master/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:48:28)\n' +
    '    at async PuppetWeChat.initBridge (file:///E:/%E6%9C%BA%E5%99%A8%E4%BA%BA/ChatGPT-wechat-bot-master/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:176:13)\n' +
    '    at async PuppetWeChat.onStart (file:///E:/%E6%9C%BA%E5%99%A8%E4%BA%BA/ChatGPT-wechat-bot-master/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:69:23)\n' +
    '    at async PuppetWeChat.start (file:///E:/%E6%9C%BA%E5%99%A8%E4%BA%BA/ChatGPT-wechat-bot-master/ChatGPT-wechat-bot-master/node_modules/state-switch/dist/esm/src/service-ctl/service-ctl.js:62:17)\n' +
    '    at async PuppetWeChat.start (file:///E:/%E6%9C%BA%E5%99%A8%E4%BA%BA/ChatGPT-wechat-bot-master/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet/dist/esm/src/mixins/service-mixin.js:18:13)'
}

进程已结束,退出代码0

**Comment by AutumnWhj** [comment]
您好 麻烦提供一下运行环境参数
