### ISSUE TITLE
Cannot build Docker image

### ISSUE THREAD

**Issue by HenryHengLUO** [AutumnWhj/ChatGPT-wechat-bot#32]
I cannot build docker image from Dockerfile.

=> ERROR [4/7] RUN npm i   && npm run puppet-install                      9.5s
------                                                                          
 > [4/7] RUN npm i   && npm run puppet-install:                                 
#9 2.499 npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead                                                              
#9 3.161 npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142                                    
#9 3.634 npm WARN deprecated har-validator@5.1.5: this library is no longer supported
#9 6.034 npm WARN deprecated puppeteer@13.7.0: < 18.1.0 is no longer supported
#9 6.697 npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
#9 9.358 npm notice 
#9 9.358 npm notice New major version of npm available! 8.19.2 -> 9.2.0
#9 9.358 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.2.0>
#9 9.358 npm notice Run `npm install -g npm@9.2.0` to update!
#9 9.358 npm notice 
#9 9.359 npm ERR! code 1
#9 9.359 npm ERR! path /code/node_modules/puppeteer
#9 9.360 npm ERR! command failed
#9 9.360 npm ERR! command sh -c -- node install.js
#9 9.360 npm ERR! The chromium binary is not available for arm64.
#9 9.360 npm ERR! If you are on Ubuntu, you can install with: 
#9 9.360 npm ERR! 
#9 9.360 npm ERR!  sudo apt install chromium
#9 9.360 npm ERR! 
#9 9.360 npm ERR! 
#9 9.360 npm ERR!  sudo apt install chromium-browser
#9 9.360 npm ERR! 
#9 9.360 npm ERR! /code/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:119
#9 9.360 npm ERR!                     throw new Error();
#9 9.360 npm ERR!                     ^
#9 9.360 npm ERR! 
#9 9.360 npm ERR! Error
#9 9.360 npm ERR!     at /code/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:119:27
#9 9.360 npm ERR!     at FSReqCallback.oncomplete (node:fs:202:21)
#9 9.361 
#9 9.361 npm ERR! A complete log of this run can be found in:
#9 9.361 npm ERR!     /root/.npm/_logs/2022-12-09T15_02_31_004Z-debug-0.log
------
executor failed running [/bin/sh -c npm i   && npm run puppet-install]: exit code: 1

#################################################################################################
My docker version is 20.10.21.
Node.JS version is v18.12.1.
NPM version is 8.19.2.

**Comment by AutumnWhj** [comment]
@HenryHengLUO  你好已解决 拉最新代码

**Comment by HenryHengLUO** [comment]
It still cannot work.


############################################################################################
=> ERROR [5/8] RUN  npm install      && npm run puppet-install                                                26.4s
------                                                                                                               
 > [5/8] RUN  npm install      && npm run puppet-install:                                                            
#10 5.602 npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead                  
#10 6.995 npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142                                                                                                             
#10 8.551 npm WARN deprecated puppeteer@13.7.0: < 18.1.0 is no longer supported                                      
#10 13.60 npm WARN deprecated har-validator@5.1.5: this library is no longer supported
#10 21.47 npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
#10 26.23 npm notice 
#10 26.23 npm notice New major version of npm available! 8.19.2 -> 9.2.0
#10 26.23 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.2.0>
#10 26.23 npm notice Run `npm install -g npm@9.2.0` to update!
#10 26.23 npm notice 
#10 26.23 npm ERR! code 1
#10 26.23 npm ERR! path /code/node_modules/puppeteer
#10 26.23 npm ERR! command failed
#10 26.23 npm ERR! command sh -c -- node install.js
#10 26.23 npm ERR! The chromium binary is not available for arm64.
#10 26.23 npm ERR! If you are on Ubuntu, you can install with: 
#10 26.23 npm ERR! 
#10 26.23 npm ERR!  sudo apt install chromium
#10 26.23 npm ERR! 
#10 26.23 npm ERR! 
#10 26.23 npm ERR!  sudo apt install chromium-browser
#10 26.23 npm ERR! 
#10 26.23 npm ERR! /code/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:119
#10 26.23 npm ERR!                     throw new Error();
#10 26.23 npm ERR!                     ^
#10 26.23 npm ERR! 
#10 26.23 npm ERR! Error
#10 26.23 npm ERR!     at /code/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:119:27
#10 26.23 npm ERR!     at FSReqCallback.oncomplete (node:fs:202:21)
#10 26.23 
#10 26.23 npm ERR! A complete log of this run can be found in:
#10 26.23 npm ERR!     /root/.npm/_logs/2022-12-11T02_40_10_972Z-debug-0.log
------
executor failed running [/bin/sh -c npm install      && npm run puppet-install]: exit code: 1
############################################################################################
ENVIRONMENT: {
  Chip: Apple M1 pro
  OS: macOS Monterey v12.3
  docker version is 20.10.21.
  Node.JS version is v18.12.1.
  NPM version is 8.19.2.
}

**Comment by hfhfn** [comment]
同样的问题, m1芯片mac

**Comment by icewolf0530** [comment]
+1
