### ISSUE TITLE
这是什么错误

### ISSUE THREAD

**Issue by miloce** [AutumnWhj/ChatGPT-wechat-bot#37]
36:05 WARN PuppetWatchdogAgent start() reset() reason: {"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}
node:events:371
      throw er; // Unhandled 'error' event
      ^

GError: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"
    at Watchdog.reset (file:///root/ChatGPT-wechat-bot/node_modules/wechaty-puppet/dist/esm/src/agents/watchdog-agent.js:45:39)
    at Watchdog.emit (node:events:394:28)
    at Timeout._onTimeout (file:///root/ChatGPT-wechat-bot/node_modules/watchdog/dist/esm/src/watchdog.js:81:18)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
Emitted 'error' event on WechatyImpl instance at:
    at WechatyImpl.emit (file:///root/ChatGPT-wechat-bot/node_modules/wechaty/dist/esm/src/wechaty-mixins/gerror-mixin.js:45:26)
    at PuppetWeChat.<anonymous> (file:///root/ChatGPT-wechat-bot/node_modules/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:155:34)
    at PuppetWeChat.emit (node:events:394:28)
    at PuppetWeChat.emit (file:///root/ChatGPT-wechat-bot/node_modules/wechaty-puppet/dist/esm/src/puppet/puppet-skeleton.js:107:22)
    at Watchdog.reset (file:///root/ChatGPT-wechat-bot/node_modules/wechaty-puppet/dist/esm/src/agents/watchdog-agent.js:45:25)
    at Watchdog.emit (node:events:394:28)
    [... lines matching original stack trace ...]
    at processTimers (node:internal/timers:500:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (file:///root/ChatGPT-wechat-bot/node_modules/wechaty-puppet/dist/esm/src/agents/watchdog-agent.js:45:39)\n' +
    '    at Watchdog.emit (node:events:394:28)\n' +
    '    at Timeout._onTimeout (file:///root/ChatGPT-wechat-bot/node_modules/watchdog/dist/esm/src/watchdog.js:81:18)\n' +
    '    at listOnTimeout (node:internal/timers:557:17)\n' +
    '    at processTimers (node:internal/timers:500:7)'
}

**Comment by AutumnWhj** [comment]
您好 能附上复现步骤 以及 执行环境参数吗
