### ISSUE TITLE
When running the " node lib/bundle.esm.js  " command, an error occurred.

### ISSUE THREAD

**Issue by ZEGEIZI** [AutumnWhj/ChatGPT-wechat-bot#38]
 ~/ChatGPT-wechat-bot-master ▓▒░───────────────────░▒▓ at 14:54:50  ─╮
❯ node lib/bundle.esm.js                                                     ─╯
14:54:56 ERR PuppetWeChatBridge start() exception: Error: net::ERR_EMPTY_RESPONSE at https://wx.qq.com?lang=zh_CN&target=t
14:54:56 ERR PuppetWeChat initBridge() exception: net::ERR_EMPTY_RESPONSE at https://wx.qq.com?lang=zh_CN&target=t
14:54:56 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.
GError: net::ERR_EMPTY_RESPONSE at https://wx.qq.com?lang=zh_CN&target=t
    at navigate (/home/gz/ChatGPT-wechat-bot-master/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:156:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FrameManager.navigateFrame (/home/gz/ChatGPT-wechat-bot-master/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:131:21)
    at async Frame.goto (/home/gz/ChatGPT-wechat-bot-master/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:512:16)
    at async Page.goto (/home/gz/ChatGPT-wechat-bot-master/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)
    at async Bridge.initPage (file:///home/gz/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:181:9)
    at async Bridge.start (file:///home/gz/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:52:25)
    at async PuppetWeChat.initBridge (file:///home/gz/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:176:13)
    at async PuppetWeChat.onStart (file:///home/gz/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:69:23)
    at async PuppetWeChat.start (file:///home/gz/ChatGPT-wechat-bot-master/node_modules/state-switch/dist/esm/src/service-ctl/service-ctl.js:62:17) {
  code: 2,
  details: 'Error: net::ERR_EMPTY_RESPONSE at https://wx.qq.com?lang=zh_CN&target=t\n' +
    '    at navigate (/home/gz/ChatGPT-wechat-bot-master/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:156:23)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async FrameManager.navigateFrame (/home/gz/ChatGPT-wechat-bot-master/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:131:21)\n' +
    '    at async Frame.goto (/home/gz/ChatGPT-wechat-bot-master/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:512:16)\n' +
    '    at async Page.goto (/home/gz/ChatGPT-wechat-bot-master/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)\n' +
    '    at async Bridge.initPage (file:///home/gz/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:181:9)\n' +
    '    at async Bridge.start (file:///home/gz/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:52:25)\n' +
    '    at async PuppetWeChat.initBridge (file:///home/gz/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:176:13)\n' +
    '    at async PuppetWeChat.onStart (file:///home/gz/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:69:23)\n' +
    '    at async PuppetWeChat.start (file:///home/gz/ChatGPT-wechat-bot-master/node_modules/state-switch/dist/esm/src/service-ctl/service-ctl.js:62:17)'

**Comment by AutumnWhj** [comment]
你好 请提供执行的环境参数
