### ISSUE TITLE
我如果想在服务器上部署的话该怎么办呀

### ISSUE THREAD

**Issue by xixicfight** [AutumnWhj/ChatGPT-wechat-bot#50]

**Comment by AutumnWhj** [comment]
按README.md文档 直接在服务器跑起来就好  https://github.com/AutumnWhj/ChatGPT-wechat-bot#use-with-docker-support-arm

**Comment by xixicfight** [comment]
是用 npm build    还是  我直接把代码丢到服务器上  然后npm run dev呢

**Comment by SnapdragonLee** [comment]
> 是用 npm build 还是 我直接把代码丢到服务器上 然后npm run dev呢

都是可以的，要是只是用的话简单一点可以先配置好 config，然后直接 `npm build`，最后 `node lib/bundle.esm.js` 。Readme 写的很清楚哦

**Comment by xixicfight** [comment]
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/root/ChatGPT-wechat-bot-master/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at Interface.<anonymous> (/root/ChatGPT-wechat-bot-master/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
    at Interface.emit (node:events:525:35)
    at Interface.close (node:readline:590:8)
    at Socket.onend (node:readline:280:10)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 2,
  details: 'Error: Failed to launch the browser process!\n' +
    '/root/ChatGPT-wechat-bot-master/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory\n' +
    '\n' +
    '\n' +
    'TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n' +
    '\n' +
    '    at onClose (/root/ChatGPT-wechat-bot-master/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)\n' +
    '    at Interface.<anonymous> (/root/ChatGPT-wechat-bot-master/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)\n' +
    '    at Interface.emit (node:events:525:35)\n' +
    '    at Interface.close (node:readline:590:8)\n' +
    '    at Socket.onend (node:readline:280:10)\n' +
    '    at Socket.emit (node:events:525:35)\n' +
    '    at endReadableNT (node:internal/streams/readable:1358:12)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:83:21)'


> > 是用npm build还是我直接把代码丢到服务器上然后npm run dev呢
> 
> 都是可以的，要是只是用的话简单一点就可以先配置好config，然后直接接入`npm build`，最后`node lib/bundle.esm.js`。Readme写的很清楚哦

**Comment by xixicfight** [comment]
报了这个错

**Comment by bcdslg** [comment]
我也报了这个错，找不到本地浏览器，docker 打包又卡着

**Comment by Hunter-0x07** [comment]
我也报了这个错，参考这个链接就可以解决了，是因为缺依赖https://www.cnblogs.com/ilizhu/p/14504049.html

**Comment by Hunter-0x07** [comment]
@xixicfight @bcdslg

**Comment by Hunter-0x07** [comment]
把所有依赖装上就不报错了
