### ISSUE TITLE
这是代理错误？

### ISSUE THREAD

**Issue by OrdinarySK** [AutumnWhj/ChatGPT-wechat-bot#62]
10:56:51 WARN PuppetWatchdogAgent start() reset() reason: {"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}
node:events:491
      throw er; // Unhandled 'error' event
      ^

GError: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"
    at Watchdog.reset (file:///F:/base/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet/dist/esm/src/agents/watchdog-agent.js:45:39)
    at Watchdog.emit (node:events:513:28)
    at Timeout._onTimeout (file:///F:/base/ChatGPT-wechat-bot-master/node_modules/watchdog/dist/esm/src/watchdog.js:81:18)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
Emitted 'error' event on WechatyImpl instance at:
    at WechatyImpl.emit (file:///F:/base/ChatGPT-wechat-bot-master/node_modules/wechaty/dist/esm/src/wechaty-mixins/gerror-mixin.js:45:26)
    at PuppetWeChat.<anonymous> (file:///F:/base/ChatGPT-wechat-bot-master/node_modules/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:155:34)
    at PuppetWeChat.emit (node:events:513:28)
    at PuppetWeChat.emit (file:///F:/base/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet/dist/esm/src/puppet/puppet-skeleton.js:107:22)
    at Watchdog.reset (file:///F:/base/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet/dist/esm/src/agents/watchdog-agent.js:45:25)
    at Watchdog.emit (node:events:513:28)
    [... lines matching original stack trace ...]
    at process.processTimers (node:internal/timers:507:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (file:///F:/base/ChatGPT-wechat-bot-master/node_modules/wechaty-puppet/dist/esm/src/agents/watchdog-agent.js:45:39)\n' +
    '    at Watchdog.emit (node:events:513:28)\n' +
    '    at Timeout._onTimeout (file:///F:/base/ChatGPT-wechat-bot-master/node_modules/watchdog/dist/esm/src/watchdog.js:81:18)\n' +
    '    at listOnTimeout (node:internal/timers:564:17)\n' +
    '    at process.processTimers (node:internal/timers:507:7)'
}

Node.js v18.12.1

**Comment by OrdinarySK** [comment]
这个问题解决了，感觉是需要实名认证。   然后部署到了railway后，发现了如下的错误：
talker: 完美向露 content: vue双向绑定的原理
Content is not within the scope of the customizition format
而且感觉速度有点慢啊

**Comment by SemiZhang** [comment]
请问timeout的配置应当在哪里修改？

**Comment by GaleForceWYL21** [comment]
> 这个问题解决了，感觉是需要实名认证。 然后部署到了railway后，发现了如下的错误：
> talker: 完美向露 content: vue双向绑定的原理
> Content is not within the scope of the customizition format
> 而且感觉速度有点慢啊

我实名认证之后还是偶尔会出现这样的问题，就是用着好好的突然就爆这个错，然后服务挂掉。请问有遇到过吗
