### ISSUE TITLE
npm run build报错

### ISSUE THREAD

**Issue by IvanMao714** [AutumnWhj/ChatGPT-wechat-bot#70]
base) ivan@ivan-Inspiron-7590:~/桌面/ChatGPT-wechat-bot$ npm run build

> chatgpt-wechatbot@1.0.0 build /home/ivan/桌面/ChatGPT-wechat-bot
> rimraf lib/* && rollup -c

[!] SyntaxError: Unexpected token ?
/home/ivan/桌面/ChatGPT-wechat-bot/node_modules/rollup-plugin-node-externals/dist/cjs/index.js:45
            const pkg = JSON.parse((await fs.promises.readFile(packagePath)).toString()) ?? {};
                                                                                          ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ivan/桌面/ChatGPT-wechat-bot/node_modules/rollup/dist/shared/loadConfigFile.js:625:17)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ivan/桌面/ChatGPT-wechat-bot/rollup.config.js:9:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chatgpt-wechatbot@1.0.0 build: `rimraf lib/* && rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chatgpt-wechatbot@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ivan/.npm/_logs/2022-12-11T13_47_07_798Z-debug.log

**Comment by TelePuryang** [comment]
尝试在code/目录下再次npm run build试下
