### ISSUE TITLE
ChatGPT invalid session token

### ISSUE THREAD

**Issue by YuxinYeIris** [AutumnWhj/ChatGPT-wechat-bot#90]
docker run --name wechatbot wechatbot:latest
file:///code/node_modules/chatgpt/build/index.js:151
      throw new ChatGPTError("ChatGPT invalid session token");
            ^

ChatGPTError: ChatGPT invalid session token
    at new ChatGPTAPI (file:///code/node_modules/chatgpt/build/index.js:151:13)
    at file:///code/lib/bundle.esm.js:60:17
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

**Comment by forever85** [comment]
I have the same.

**Comment by AnkitPandey007** [comment]
+1 for error
