### ISSUE TITLE
ChatGPT failed to refresh auth token.

### ISSUE THREAD

**Issue by pigmeetsomebody** [AutumnWhj/ChatGPT-wechat-bot#91]
你好，本地运行报错是什么原因呢

**Comment by wangchaofan2018** [comment]
我也出现了 在下面粘一下我的报错信息。
`(node:4422) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
retry 1 times, error: Error: ChatGPT failed to refresh auth token. Error: 403 Forbidden
retry 2 times, error: Error: ChatGPT failed to refresh auth token. Error: 403 Forbidden
retry 3 times, error: Error: ChatGPT failed to refresh auth token. Error: 403 Forbidden
ChatGPTError: ChatGPT failed to refresh auth token. Error: 403 Forbidden
    at ChatGPTAPI.refreshAccessToken (file:///Users/wangchaofan/github/ChatGPT-wechat-bot/node_modules/chatgpt/build/index.js:313:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTAPI.sendMessage (file:///Users/wangchaofan/github/ChatGPT-wechat-bot/node_modules/chatgpt/build/index.js:171:25)
    at async file:///Users/wangchaofan/github/ChatGPT-wechat-bot/node_modules/p-timeout/index.js:92:13 {
  response: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 403,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Forbidden',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: HeadersList(32) [
      'alt-svc',
      'h3=":443"; ma=86400, h3-29=":443"; ma=86400',
      'cache-control',
      'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
      'cf-chl-bypass',
      '1',
      'cf-ray',
      '7790714d6f21fafc-SJC',
      'connection',
      'close',
      'content-encoding',
      'gzip',
      'content-type',
      'text/html; charset=UTF-8',
      'date',
      'Tue, 13 Dec 2022 17:33:02 GMT',
      'expires',
      'Thu, 01 Jan 1970 00:00:01 GMT',
      'permissions-policy',
      'accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()',
      'referrer-policy',
      'same-origin',
      'server',
      'cloudflare',
      'set-cookie',
      '__cf_bm=H0wYUCJsp_YSWl6k9QcA5rAMP3N.R3pppAfmzviRKWE-1670952782-0-AURrri1/roCeSees1luGzuhKeTgv8yT5EtcSdwi/Au1x2Uu1ZtHAqNT/zEXPK+CqyLn21C4/avMEQHQF8CfimqU=; path=/; expires=Tue, 13-Dec-22 18:03:02 GMT; domain=.chat.openai.com; HttpOnly; Secure; SameSite=None',
      'transfer-encoding',
      'chunked',
      'vary',
      'Accept-Encoding',
      'x-frame-options',
      'SAMEORIGIN'
    ]
  },
  statusCode: 403,
  statusText: 'Forbidden',
  originalError: ChatGPTError: 403 Forbidden
      at file:///Users/wangchaofan/github/ChatGPT-wechat-bot/node_modules/chatgpt/build/index.js:275:25
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async ChatGPTAPI.refreshAccessToken (file:///Users/wangchaofan/github/ChatGPT-wechat-bot/node_modules/chatgpt/build/index.js:267:19)
      at async ChatGPTAPI.sendMessage (file:///Users/wangchaofan/github/ChatGPT-wechat-bot/node_modules/chatgpt/build/index.js:171:25)
      at async file:///Users/wangchaofan/github/ChatGPT-wechat-bot/node_modules/p-timeout/index.js:92:13 {
    response: Response {
      [Symbol(realm)]: null,
      [Symbol(state)]: [Object],
      [Symbol(headers)]: [HeadersList]
    },
    statusCode: 403,
    statusText: 'Forbidden'
  }
}

`
